<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} --strict --tags ~@wip"
%>
default: --drb --port 8991 <%= std_opts %> features --tags ~@selenium
wip: --drb --port 8991 --tags @wip:3 --wip features
rerun: --drb --port 8991 <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip
selenium: features --tags @selenium
